# Generated by Django 5.1.7 on 2025-03-14 13:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_date_naissance_alter_profile_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/image.jpg', upload_to='profile_pics'),
        ),
    ]
