# Generated by Django 5.1.3 on 2025-03-14 18:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[users.models.validate_esi_sba_email])),
            ],
        ),
    ]
