# Generated by Django 5.1.3 on 2025-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_listepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('ATS', 'ATS'), ('medecin', 'Médecin'), ('assistant_medical', 'Assistant Médical'), ('directeur', 'Directeur')], default='etudiant', max_length=20),
        ),
    ]
